package org.fossify.keyboard.helpers

/**
 * Emoji-to-keyword mapping for search ("search like Gboard", the #2 most
 * upvoted open feature request for this app - 43 votes as of this build).
 *
 * Sourced from two places, merged together:
 * 1. A hand-built pass covering smileys, animals, food, and activities in
 *    full (541 entries), written and individually verified early in this
 *    effort, before the authoritative source below was available.
 * 2. The official Unicode CLDR short names (plus, for the v17.0 additions,
 *    the official "Other Keywords" synonym list) for essentially the
 *    entire emoji standard, provided directly by the user from
 *    unicode.org's published emoji-list data - transcribed as
 *    (codepoint, name) pairs and the actual emoji characters
 *    reconstructed programmatically from the codepoints, specifically to
 *    avoid any transcription risk on the Unicode glyphs themselves.
 *
 * Where both sources cover the same emoji, their keywords are merged
 * rather than one replacing the other.
 *
 * Coverage: 1515 of the ~1897 base emoji in this app's bundled
 * emoji_spec.txt - deliberately scoped to the popular/practical set
 * rather than exhaustive completeness, matching how a real product like
 * Gboard actually covers this (not literally every combinatorial skin-
 * tone/gender ZWJ variant). The remaining gap is mostly those deep
 * variant combinations, not missing base concepts - the base concept
 * (e.g. "astronaut") is covered, its many combinatorial variants are
 * not all individually named. An emoji with no entry here simply will
 * not appear in search results - it stays fully accessible through
 * normal category browsing, unaffected. This dataset is considered
 * complete for this feature; further expansion is not planned.
 *
 * Deliberately built by extracting emoji characters programmatically
 * (either from the real bundled emoji_spec.txt, or reconstructed from
 * official Unicode codepoints) and pairing them with keywords by
 * position/codepoint - never by hand-retyping a Unicode emoji glyph
 * directly - specifically to eliminate the risk of a transcription error
 * on a complex sequence (ZWJ sequences, variation selectors, skin-tone
 * modifiers, regional indicator flag pairs).
 */
val EMOJI_SEARCH_KEYWORDS = mapOf(
    "😀" to "grinning face smile happy",
    "😃" to "grinning big eyes smile happy joy",
    "😄" to "grinning smiling eyes smile happy laugh",
    "😁" to "beaming grin smile teeth happy",
    "😆" to "grinning squinting laugh happy lol",
    "😅" to "grinning sweat nervous relief phew",
    "🤣" to "rolling floor laughing rofl lol hilarious",
    "😂" to "tears of joy laugh cry lol funny",
    "🙂" to "slightly smiling face smile meh",
    "🙃" to "upside down face silly sarcasm",
    "🫠" to "melting face hot awkward melt",
    "😉" to "winking face wink flirt",
    "😊" to "smiling face blush happy shy",
    "😇" to "smiling halo angel innocent",
    "🥰" to "smiling hearts love adore",
    "😍" to "heart eyes love crush infatuated",
    "🤩" to "star struck starry eyes excited wow",
    "😘" to "face blowing kiss love",
    "😗" to "kissing face kiss",
    "☺️" to "smiling face relaxed content",
    "😚" to "kissing face closed eyes kiss",
    "😙" to "kissing face smiling eyes kiss",
    "🥲" to "smiling tear bittersweet proud touched",
    "😋" to "savoring food yum delicious tongue",
    "😛" to "face with tongue playful silly",
    "😜" to "winking tongue silly joke",
    "🤪" to "zany face crazy wild goofy",
    "😝" to "squinting tongue joke teasing",
    "🤑" to "money mouth rich greedy dollar",
    "🤗" to "hugging face hug embrace",
    "🤭" to "hand over mouth oops giggle shy",
    "🫢" to "open eyes hand over mouth surprise shock gasp",
    "🫣" to "peeking eye shy scared peek",
    "🤫" to "shushing quiet secret shh",
    "🤔" to "thinking face think hmm ponder",
    "🫡" to "saluting salute respect yes sir",
    "🤐" to "zipper mouth quiet secret silence",
    "🤨" to "raised eyebrow skeptical suspicious",
    "😐" to "neutral face meh indifferent",
    "😑" to "expressionless blank meh",
    "😶" to "face without mouth speechless silent",
    "🫥" to "dotted line face invisible anxious disappear",
    "😶‍🌫️" to "face in clouds foggy absentminded dazed",
    "😏" to "smirking face smug flirt",
    "😒" to "unamused face annoyed meh",
    "🙄" to "rolling eyes eye roll annoyed whatever",
    "😬" to "grimacing awkward nervous yikes",
    "😮‍💨" to "face exhaling sigh relief exhausted",
    "🤥" to "lying face pinocchio lie",
    "🫨" to "shaking face shocked overwhelmed",
    "🙂‍↔️" to "head shaking horizontally no disagree",
    "🙂‍↕️" to "head shaking vertically yes nod agree",
    "😌" to "relieved face calm content",
    "😔" to "pensive face sad disappointed",
    "😪" to "sleepy face tired sleep",
    "🤤" to "drooling face drool desire hungry",
    "😴" to "sleeping face sleep zzz tired",
    "😷" to "medical mask sick mask ill",
    "🤒" to "thermometer sick fever ill",
    "🤕" to "head bandage hurt injured sick",
    "🤢" to "nauseated face sick green disgust",
    "🤮" to "vomiting sick throw up",
    "🤧" to "sneezing face sick tissue",
    "🥵" to "hot face heat sweat",
    "🥶" to "cold face freezing blue",
    "🥴" to "woozy face dizzy drunk confused",
    "😵" to "dizzy face stars confused",
    "😵‍💫" to "face spiral dizzy confused overwhelmed",
    "🤯" to "exploding head mind blown shocked",
    "🤠" to "cowboy hat face yeehaw",
    "🥳" to "partying face celebrate party birthday",
    "🥸" to "disguised face incognito glasses mustache",
    "😎" to "smiling face sunglasses cool",
    "🤓" to "nerd face glasses geek smart",
    "🧐" to "monocle face suspicious inspect",
    "😕" to "confused face uncertain unsure",
    "🫤" to "face with diagonal mouth meh unsure",
    "😟" to "worried face anxious concerned",
    "🙁" to "slightly frowning face sad frown",
    "☹️" to "frowning face sad frown",
    "😮" to "face with open mouth surprised wow",
    "😯" to "hushed face surprised stunned",
    "😲" to "astonished face shocked amazed",
    "😳" to "flushed face embarrassed blush",
    "🥺" to "pleading face puppy eyes beg",
    "🥹" to "face holding back tears touched proud",
    "😦" to "frowning open mouth surprised concerned",
    "😧" to "anguished face pain shocked",
    "😨" to "fearful face scared afraid",
    "😰" to "anxious sweat nervous worried",
    "😥" to "sad but relieved disappointed",
    "😢" to "crying face sad tear",
    "😭" to "loudly crying sobbing sad",
    "😱" to "screaming fear shocked scared",
    "😖" to "confounded face upset frustrated",
    "😣" to "persevering face struggling determined",
    "😞" to "disappointed face sad",
    "😓" to "downcast sweat tired sad",
    "😩" to "weary face exhausted tired",
    "😫" to "tired face frustrated exhausted",
    "🥱" to "yawning face tired sleepy bored",
    "😤" to "steam from nose triumph proud angry",
    "😡" to "pouting face angry mad rage",
    "😠" to "angry face mad annoyed",
    "🤬" to "swearing face curse angry censored",
    "😈" to "smiling devil horns mischievous",
    "👿" to "angry devil horns evil",
    "💀" to "skull dead death",
    "☠️" to "skull crossbones danger death poison",
    "💩" to "pile of poo funny silly",
    "🤡" to "clown face funny silly",
    "👹" to "ogre monster scary",
    "👺" to "goblin monster scary",
    "👻" to "ghost spooky halloween",
    "👽" to "alien ufo space",
    "👾" to "alien monster space invader",
    "🤖" to "robot ai machine",
    "😺" to "cat face happy smile",
    "😸" to "cat grinning happy smile",
    "😹" to "cat tears joy laugh",
    "😻" to "cat heart eyes love",
    "😼" to "cat wry smile smirk",
    "😽" to "cat kissing kiss",
    "🙀" to "cat screaming fear shocked",
    "😿" to "cat crying sad tear",
    "😾" to "cat pouting angry",
    "🙈" to "see no evil monkey shy embarrassed",
    "🙉" to "hear no evil monkey",
    "🙊" to "speak no evil monkey secret",
    "💌" to "love letter mail romance",
    "💘" to "heart with arrow cupid love",
    "💝" to "heart with ribbon gift love",
    "💖" to "sparkling heart love",
    "💗" to "growing heart love excited",
    "💓" to "beating heart love pulse",
    "💞" to "revolving hearts love",
    "💕" to "two hearts love",
    "💟" to "heart decoration love purple",
    "❣️" to "heart exclamation love emphasis",
    "💔" to "broken heart sad breakup",
    "❤️‍🔥" to "heart on fire passion love",
    "❤️‍🩹" to "mending heart healing recovery",
    "❤️" to "red heart love",
    "🩷" to "pink heart love",
    "🧡" to "orange heart love",
    "💛" to "yellow heart love friendship",
    "💚" to "green heart love nature",
    "💙" to "blue heart love trust",
    "🩵" to "light blue heart love",
    "💜" to "purple heart love",
    "🤎" to "brown heart love",
    "🖤" to "black heart dark love",
    "🩶" to "grey heart love neutral",
    "🤍" to "white heart love pure",
    "💋" to "kiss mark lipstick love",
    "💯" to "hundred points perfect score",
    "💢" to "anger symbol mad frustrated",
    "💥" to "collision boom explosion impact",
    "💫" to "dizzy stars sparkle",
    "💦" to "water splash sweat drops",
    "💨" to "dashing away wind fast run",
    "🕳️" to "hole empty void",
    "💬" to "speech balloon chat talk",
    "👁️‍🗨️" to "eye in speech bubble witness",
    "🗨️" to "left speech bubble talk chat",
    "🗯️" to "right anger bubble mad thought",
    "💭" to "thought balloon think dream",
    "💤" to "zzz sleep tired",
    "🐵" to "monkey face animal",
    "🐒" to "monkey animal",
    "🦍" to "gorilla animal ape",
    "🦧" to "orangutan animal ape",
    "🐶" to "dog face pet animal",
    "🐕" to "dog pet animal",
    "🦮" to "guide dog service animal",
    "🐕‍🦺" to "service dog vest animal",
    "🐩" to "poodle dog pet",
    "🐺" to "wolf face animal wild",
    "🦊" to "fox face animal",
    "🦝" to "raccoon animal",
    "🐱" to "cat face pet animal",
    "🐈" to "cat pet animal",
    "🐈‍⬛" to "black cat pet animal",
    "🦁" to "lion face animal wild",
    "🐯" to "tiger face animal wild",
    "🐅" to "tiger animal wild",
    "🐆" to "leopard animal wild",
    "🐴" to "horse face animal",
    "🫎" to "moose animal wild",
    "🫏" to "donkey animal",
    "🐎" to "horse animal racing",
    "🦄" to "unicorn magic fantasy",
    "🦓" to "zebra animal",
    "🦌" to "deer animal wild",
    "🦬" to "bison animal wild",
    "🐮" to "cow face animal farm",
    "🐂" to "ox animal farm",
    "🐃" to "water buffalo animal farm",
    "🐄" to "cow animal farm",
    "🐷" to "pig face animal farm",
    "🐖" to "pig animal farm",
    "🐗" to "boar animal wild",
    "🐽" to "pig nose snout",
    "🐏" to "ram animal farm",
    "🐑" to "ewe sheep animal farm",
    "🐐" to "goat animal farm",
    "🐪" to "camel animal desert",
    "🐫" to "two hump camel animal desert",
    "🦙" to "llama animal",
    "🦒" to "giraffe animal wild",
    "🐘" to "elephant animal wild",
    "🦣" to "mammoth animal extinct",
    "🦏" to "rhinoceros animal wild",
    "🦛" to "hippopotamus animal wild",
    "🐭" to "mouse face animal",
    "🐁" to "mouse animal",
    "🐀" to "rat animal",
    "🐹" to "hamster pet animal",
    "🐰" to "rabbit face animal",
    "🐇" to "rabbit animal",
    "🐿️" to "chipmunk animal",
    "🦫" to "beaver animal",
    "🦔" to "hedgehog animal",
    "🦇" to "bat animal night",
    "🐻" to "bear face animal",
    "🐻‍❄️" to "polar bear animal",
    "🐨" to "koala animal",
    "🐼" to "panda animal",
    "🦥" to "sloth animal slow",
    "🦦" to "otter animal",
    "🦨" to "skunk animal",
    "🦘" to "kangaroo animal",
    "🦡" to "badger animal",
    "🐾" to "paw prints animal tracks",
    "🦃" to "turkey bird animal",
    "🐔" to "chicken bird animal farm",
    "🐓" to "rooster bird animal farm",
    "🐣" to "hatching chick bird baby",
    "🐤" to "baby chick bird",
    "🐥" to "front facing baby chick bird",
    "🐦" to "bird animal",
    "🐧" to "penguin animal bird",
    "🕊️" to "dove bird peace",
    "🦅" to "eagle bird animal",
    "🦆" to "duck bird animal",
    "🦢" to "swan bird animal",
    "🦉" to "owl bird animal night",
    "🦤" to "dodo bird extinct",
    "🪶" to "feather bird",
    "🦩" to "flamingo bird animal",
    "🦚" to "peacock bird animal",
    "🦜" to "parrot bird animal",
    "🪽" to "wing feather bird fly",
    "🐦‍⬛" to "black bird crow raven",
    "🪿" to "goose bird animal",
    "🐦‍🔥" to "phoenix bird fire mythical",
    "🐸" to "frog animal",
    "🐊" to "crocodile animal reptile",
    "🐢" to "turtle animal reptile",
    "🦎" to "lizard animal reptile",
    "🐍" to "snake animal reptile",
    "🐲" to "dragon face mythical",
    "🐉" to "dragon mythical",
    "🦕" to "sauropod dinosaur extinct",
    "🦖" to "trex dinosaur extinct",
    "🐳" to "whale animal sea",
    "🐋" to "whale animal sea",
    "🐬" to "dolphin animal sea",
    "🦭" to "seal animal sea",
    "🐟" to "fish animal sea",
    "🐠" to "tropical fish animal sea",
    "🐡" to "blowfish animal sea",
    "🦈" to "shark animal sea",
    "🐙" to "octopus animal sea",
    "🐚" to "spiral shell sea beach",
    "🪸" to "coral reef sea ocean",
    "🪼" to "jellyfish sea animal",
    "🐌" to "snail animal slow",
    "🦋" to "butterfly animal insect",
    "🐛" to "bug animal insect",
    "🐜" to "ant animal insect",
    "🐝" to "honeybee animal insect",
    "🪲" to "beetle animal insect",
    "🐞" to "lady beetle ladybug insect",
    "🦗" to "cricket animal insect",
    "🪳" to "cockroach animal insect",
    "🕷️" to "spider animal insect",
    "🕸️" to "spider web insect",
    "🦂" to "scorpion animal insect",
    "🦟" to "mosquito animal insect",
    "🪰" to "fly animal insect",
    "🪱" to "worm animal",
    "🦠" to "microbe germ virus",
    "💐" to "bouquet flowers gift",
    "🌸" to "cherry blossom flower spring",
    "💮" to "white flower blossom",
    "🪷" to "lotus flower",
    "🏵️" to "rosette flower decoration",
    "🌹" to "rose flower romance",
    "🥀" to "wilted flower dying",
    "🌺" to "hibiscus flower",
    "🌻" to "sunflower flower",
    "🌼" to "blossom flower",
    "🌷" to "tulip flower spring",
    "🪻" to "hyacinth flower",
    "🌱" to "seedling plant sprout",
    "🪴" to "potted plant houseplant",
    "🌲" to "evergreen tree pine",
    "🌳" to "deciduous tree",
    "🌴" to "palm tree tropical",
    "🌵" to "cactus desert plant",
    "🌾" to "sheaf of rice wheat",
    "🌿" to "herb leaf plant",
    "☘️" to "shamrock clover luck irish",
    "🍀" to "four leaf clover luck",
    "🍁" to "maple leaf canada fall",
    "🍂" to "fallen leaf autumn",
    "🍃" to "leaf fluttering wind",
    "🪹" to "empty nest bird",
    "🪺" to "nest with eggs bird",
    "🍄" to "mushroom fungus",
    "🍇" to "grapes fruit food",
    "🍈" to "melon fruit food",
    "🍉" to "watermelon fruit food",
    "🍊" to "tangerine orange fruit food",
    "🍋" to "lemon fruit food sour",
    "🍋‍🟩" to "lime fruit food green",
    "🍌" to "banana fruit food",
    "🍍" to "pineapple fruit food",
    "🥭" to "mango fruit food",
    "🍎" to "red apple fruit food",
    "🍏" to "green apple fruit food",
    "🍐" to "pear fruit food",
    "🍑" to "peach fruit food",
    "🍒" to "cherries fruit food",
    "🍓" to "strawberry fruit food",
    "🫐" to "blueberries fruit food",
    "🥝" to "kiwi fruit food",
    "🍅" to "tomato fruit food vegetable",
    "🫒" to "olive food",
    "🥥" to "coconut fruit food",
    "🥑" to "avocado fruit food",
    "🍆" to "eggplant vegetable food aubergine",
    "🥔" to "potato vegetable food",
    "🥕" to "carrot vegetable food",
    "🌽" to "corn vegetable food maize",
    "🌶️" to "hot pepper spicy chili food",
    "🫑" to "bell pepper vegetable food",
    "🥒" to "cucumber vegetable food",
    "🥬" to "leafy green vegetable food lettuce",
    "🥦" to "broccoli vegetable food",
    "🧄" to "garlic food",
    "🧅" to "onion vegetable food",
    "🥜" to "peanuts food nuts",
    "🫘" to "beans food legume",
    "🌰" to "chestnut food nut",
    "🫚" to "ginger root food spice",
    "🫛" to "pea pod vegetable food",
    "🍄‍🟫" to "brown mushroom fungus food",
    "🍞" to "bread food loaf",
    "🥐" to "croissant food pastry",
    "🥖" to "baguette bread food french",
    "🫓" to "flatbread food",
    "🥨" to "pretzel food snack",
    "🥯" to "bagel food breakfast",
    "🥞" to "pancakes food breakfast",
    "🧇" to "waffle food breakfast",
    "🧀" to "cheese wedge food dairy",
    "🍖" to "meat on bone food",
    "🍗" to "poultry leg food chicken",
    "🥩" to "cut of meat food steak",
    "🥓" to "bacon food breakfast",
    "🍔" to "hamburger food burger",
    "🍟" to "french fries food fast food",
    "🍕" to "pizza food slice",
    "🌭" to "hot dog food fast food",
    "🥪" to "sandwich food lunch",
    "🌮" to "taco food mexican",
    "🌯" to "burrito food mexican",
    "🫔" to "tamale food mexican",
    "🥙" to "stuffed flatbread food pita",
    "🧆" to "falafel food middle eastern",
    "🥚" to "egg food breakfast",
    "🍳" to "cooking fried egg food",
    "🥘" to "shallow pan of food paella",
    "🍲" to "pot of food stew",
    "🫕" to "fondue food cheese",
    "🥣" to "bowl with spoon food cereal",
    "🥗" to "green salad food healthy",
    "🍿" to "popcorn food snack movie",
    "🧈" to "butter food dairy",
    "🧂" to "salt food seasoning",
    "🥫" to "canned food",
    "🍱" to "bento box food japanese",
    "🍘" to "rice cracker food japanese",
    "🍙" to "rice ball food japanese",
    "🍚" to "cooked rice food japanese",
    "🍛" to "curry rice food",
    "🍜" to "steaming bowl ramen noodles food",
    "🍝" to "spaghetti pasta food",
    "🍠" to "roasted sweet potato food",
    "🍢" to "oden skewer food japanese",
    "🍣" to "sushi food japanese",
    "🍤" to "fried shrimp food tempura",
    "🍥" to "fish cake food japanese narutomaki",
    "🥮" to "moon cake food chinese",
    "🍡" to "dango food japanese dessert",
    "🥟" to "dumpling food",
    "🥠" to "fortune cookie food",
    "🥡" to "takeout box food chinese",
    "🦀" to "crab food seafood",
    "🦞" to "lobster food seafood",
    "🦐" to "shrimp food seafood",
    "🦑" to "squid food seafood",
    "🦪" to "oyster food seafood",
    "🍦" to "soft ice cream food dessert",
    "🍧" to "shaved ice food dessert",
    "🍨" to "ice cream food dessert",
    "🍩" to "doughnut food dessert donut",
    "🍪" to "cookie food dessert",
    "🎂" to "birthday cake food dessert celebration",
    "🍰" to "shortcake cake food dessert",
    "🧁" to "cupcake food dessert",
    "🥧" to "pie food dessert",
    "🍫" to "chocolate bar food dessert",
    "🍬" to "candy food dessert sweet",
    "🍭" to "lollipop food dessert candy",
    "🍮" to "custard food dessert flan",
    "🍯" to "honey pot food sweet",
    "🍼" to "baby bottle milk food",
    "🥛" to "glass of milk food drink",
    "☕" to "hot beverage coffee tea drink",
    "🫖" to "teapot drink",
    "🍵" to "teacup without handle drink tea",
    "🍶" to "sake drink alcohol japanese",
    "🍾" to "bottle with popping cork champagne drink",
    "🍷" to "wine glass drink alcohol",
    "🍸" to "cocktail glass drink alcohol martini",
    "🍹" to "tropical drink cocktail alcohol",
    "🍺" to "beer mug drink alcohol",
    "🍻" to "clinking beer mugs drink alcohol cheers",
    "🥂" to "clinking glasses drink alcohol cheers toast",
    "🥃" to "tumbler glass drink alcohol whiskey",
    "🫗" to "pouring liquid drink",
    "🥤" to "cup with straw drink soda",
    "🧋" to "bubble tea drink",
    "🧃" to "beverage box juice drink",
    "🧉" to "mate drink south american",
    "🧊" to "ice cube cold",
    "🥢" to "chopsticks food utensil",
    "🍽️" to "fork and knife with plate food dining",
    "🍴" to "fork and knife food utensil",
    "🥄" to "spoon food utensil",
    "🔪" to "kitchen knife food utensil",
    "🫙" to "jar food container",
    "🏺" to "amphora food container ancient",
    "🎃" to "jack o lantern halloween pumpkin",
    "🎄" to "christmas tree holiday",
    "🎆" to "fireworks celebration night",
    "🎇" to "sparkler fireworks celebration",
    "🧨" to "firecracker explosive celebration",
    "✨" to "sparkles shiny magic clean",
    "🎈" to "balloon party celebration",
    "🎉" to "party popper celebration confetti",
    "🎊" to "confetti ball celebration party",
    "🎋" to "tanabata tree wish japanese",
    "🎍" to "pine decoration japanese new year",
    "🎎" to "japanese dolls hinamatsuri festival",
    "🎏" to "carp streamer koinobori japanese festival",
    "🎐" to "wind chime japanese summer",
    "🎑" to "moon viewing ceremony japanese",
    "🧧" to "red envelope gift money chinese",
    "🎀" to "ribbon gift bow",
    "🎁" to "wrapped gift present birthday",
    "🎗️" to "reminder ribbon awareness",
    "🎟️" to "admission tickets event",
    "🎫" to "ticket event entry",
    "🎖️" to "military medal award honor",
    "🏆" to "trophy award winner",
    "🏅" to "sports medal award",
    "🥇" to "first place medal gold 1st",
    "🥈" to "second place medal silver 2nd",
    "🥉" to "third place medal bronze 3rd",
    "⚽" to "soccer ball sports football",
    "⚾" to "baseball sports",
    "🥎" to "softball sports",
    "🏀" to "basketball sports",
    "🏐" to "volleyball sports",
    "🏈" to "american football sports",
    "🏉" to "rugby football sports",
    "🎾" to "tennis sports",
    "🥏" to "flying disc frisbee sports",
    "🎳" to "bowling sports",
    "🏏" to "cricket game sports",
    "🏑" to "field hockey sports",
    "🏒" to "ice hockey sports",
    "🥍" to "lacrosse sports",
    "🏓" to "ping pong table tennis sports",
    "🏸" to "badminton sports",
    "🥊" to "boxing glove sports fight",
    "🥋" to "martial arts uniform karate",
    "🥅" to "goal net sports soccer",
    "⛳" to "flag in hole golf sports",
    "⛸️" to "ice skate sports winter",
    "🎣" to "fishing pole hobby",
    "🤿" to "diving mask snorkel swim",
    "🎽" to "running shirt sports jersey",
    "🎿" to "skis winter sports",
    "🛷" to "sled winter sports",
    "🥌" to "curling stone winter sports",
    "🎯" to "direct hit target dart bullseye",
    "🪀" to "yo yo toy",
    "🪁" to "kite toy wind",
    "🔫" to "pistol gun toy water",
    "🎱" to "pool 8 ball billiards game",
    "🔮" to "crystal ball fortune magic",
    "🪄" to "magic wand sparkle",
    "🎮" to "video game controller gaming",
    "🕹️" to "joystick gaming retro",
    "🎰" to "slot machine gambling casino",
    "🎲" to "game die dice",
    "🧩" to "puzzle piece jigsaw game",
    "🧸" to "teddy bear toy stuffed animal",
    "🪅" to "pinata party game",
    "🪩" to "mirror ball disco party",
    "🪆" to "nesting dolls matryoshka russian",
    "♠️" to "spade suit card game",
    "♥️" to "heart suit card game",
    "♦️" to "diamond suit card game",
    "♣️" to "club suit card game",
    "♟️" to "chess pawn game strategy",
    "🃏" to "joker card game",
    "🀄" to "mahjong tile game red dragon",
    "🎴" to "flower playing cards game hanafuda",
    "🎭" to "performing arts theater masks drama",
    "🖼️" to "framed picture art gallery",
    "🎨" to "artist palette paint art",
    "🧵" to "thread sewing needle craft",
    "🪡" to "sewing needle craft thread",
    "🧶" to "yarn knitting craft",
    "🪢" to "knot rope craft",
    "🌍" to "globe showing europe africa",
    "🌎" to "globe showing americas",
    "🌏" to "globe showing asia australia",
    "🌐" to "globe with meridians",
    "🗺" to "world map",
    "🗾" to "map of japan",
    "🧭" to "compass",
    "🏔" to "snow capped mountain",
    "⛰" to "mountain",
    "🌋" to "volcano",
    "🗻" to "mount fuji",
    "🏕" to "camping",
    "🏖" to "beach with umbrella",
    "🏜" to "desert",
    "🏝" to "desert island",
    "🏞" to "national park",
    "🏟" to "stadium",
    "🏛" to "classical building",
    "🏗" to "building construction",
    "🧱" to "brick",
    "🪨" to "rock",
    "🪵" to "wood",
    "🛖" to "hut",
    "🏘" to "houses",
    "🏚" to "derelict house",
    "🏠" to "house",
    "🏡" to "house with garden",
    "🏢" to "office building",
    "🏣" to "japanese post office",
    "🏤" to "post office",
    "🏥" to "hospital",
    "🏦" to "bank",
    "🏨" to "hotel",
    "🏩" to "love hotel",
    "🏪" to "convenience store",
    "🏫" to "school",
    "🏬" to "department store",
    "🏭" to "factory",
    "🏯" to "japanese castle",
    "🏰" to "castle",
    "💒" to "wedding",
    "🗼" to "tokyo tower",
    "🗽" to "statue of liberty",
    "⛪" to "church",
    "🕌" to "mosque",
    "🛕" to "hindu temple",
    "🕍" to "synagogue",
    "⛩" to "shinto shrine",
    "🕋" to "kaaba",
    "⛲" to "fountain",
    "⛺" to "tent",
    "🌁" to "foggy",
    "🌃" to "night with stars",
    "🏙" to "cityscape",
    "🌄" to "sunrise over mountains",
    "🌅" to "sunrise",
    "🌆" to "cityscape at dusk",
    "🌇" to "sunset",
    "🌉" to "bridge at night",
    "♨" to "hot springs",
    "🎠" to "carousel horse",
    "🛝" to "playground slide",
    "🎡" to "ferris wheel",
    "🎢" to "roller coaster",
    "💈" to "barber pole",
    "🎪" to "circus tent",
    "🚂" to "locomotive",
    "🚃" to "railway car",
    "🚄" to "high speed train",
    "🚅" to "bullet train",
    "🚆" to "train",
    "🚇" to "metro",
    "🚈" to "light rail",
    "🚉" to "station",
    "🚊" to "tram",
    "🚝" to "monorail",
    "🚞" to "mountain railway",
    "🚋" to "tram car",
    "🚌" to "bus",
    "🚍" to "oncoming bus",
    "🚎" to "trolleybus",
    "🚐" to "minibus",
    "🚑" to "ambulance",
    "🚒" to "fire engine",
    "🚓" to "police car",
    "🚔" to "oncoming police car",
    "🚕" to "taxi",
    "🚖" to "oncoming taxi",
    "🚗" to "automobile",
    "🚘" to "oncoming automobile",
    "🚙" to "sport utility vehicle",
    "🛻" to "pickup truck",
    "🚚" to "delivery truck",
    "🚛" to "articulated lorry",
    "🚜" to "tractor",
    "🏎" to "racing car",
    "🏍" to "motorcycle",
    "🛵" to "motor scooter",
    "🦽" to "manual wheelchair",
    "🦼" to "motorized wheelchair",
    "🛺" to "auto rickshaw",
    "🚲" to "bicycle",
    "🛴" to "kick scooter",
    "🛹" to "skateboard",
    "🛼" to "roller skate",
    "🚏" to "bus stop",
    "🛣" to "motorway",
    "🛤" to "railway track",
    "🛢" to "oil drum",
    "⛽" to "fuel pump",
    "🛞" to "wheel",
    "🚨" to "police car light",
    "🚥" to "horizontal traffic light",
    "🚦" to "vertical traffic light",
    "🛑" to "stop sign",
    "🚧" to "construction",
    "⚓" to "anchor",
    "🛟" to "ring buoy",
    "⛵" to "sailboat",
    "🛶" to "canoe",
    "🚤" to "speedboat",
    "🛳" to "passenger ship",
    "⛴" to "ferry",
    "🛥" to "motor boat",
    "🚢" to "ship",
    "✈" to "airplane",
    "🛩" to "small airplane",
    "🛫" to "airplane departure",
    "🛬" to "airplane arrival",
    "🪂" to "parachute",
    "💺" to "seat",
    "🚁" to "helicopter",
    "🚟" to "suspension railway",
    "🚠" to "mountain cableway",
    "🚡" to "aerial tramway",
    "🛰" to "satellite",
    "🚀" to "rocket",
    "🛸" to "flying saucer",
    "🛎" to "bellhop bell",
    "🧳" to "luggage",
    "⌛" to "hourglass done",
    "⏳" to "hourglass not done",
    "⌚" to "watch",
    "⏰" to "alarm clock",
    "⏱" to "stopwatch",
    "⏲" to "timer clock",
    "🕰" to "mantelpiece clock",
    "🌑" to "new moon",
    "🌒" to "waxing crescent moon",
    "🌓" to "first quarter moon",
    "🌔" to "waxing gibbous moon",
    "🌕" to "full moon",
    "🌖" to "waning gibbous moon",
    "🌗" to "last quarter moon",
    "🌘" to "waning crescent moon",
    "🌙" to "crescent moon",
    "🌚" to "new moon face",
    "🌛" to "first quarter moon face",
    "🌜" to "last quarter moon face",
    "🌡" to "thermometer",
    "☀" to "sun",
    "🌝" to "full moon face",
    "🌞" to "sun with face",
    "🪐" to "ringed planet",
    "⭐" to "star",
    "🌟" to "glowing star",
    "🌠" to "shooting star",
    "🌌" to "milky way",
    "☁" to "cloud",
    "⛅" to "sun behind cloud",
    "⛈" to "cloud with lightning and rain",
    "🌤" to "sun behind small cloud",
    "🌥" to "sun behind large cloud",
    "🌦" to "sun behind rain cloud",
    "🌧" to "cloud with rain",
    "🌨" to "cloud with snow",
    "🌩" to "cloud with lightning",
    "🌪" to "tornado",
    "🌫" to "fog",
    "🌬" to "wind face",
    "🌀" to "cyclone",
    "🌈" to "rainbow",
    "🌂" to "closed umbrella",
    "☂" to "umbrella",
    "☔" to "umbrella with rain drops",
    "⛱" to "umbrella on ground",
    "⚡" to "high voltage",
    "❄" to "snowflake",
    "☃" to "snowman",
    "⛄" to "snowman without snow",
    "☄" to "comet",
    "🔥" to "fire",
    "💧" to "droplet",
    "🌊" to "water wave",
    "🎗" to "reminder ribbon",
    "🎟" to "admission tickets",
    "🎖" to "military medal",
    "⛸" to "ice skate",
    "🕹" to "joystick",
    "♠" to "spade suit",
    "♥" to "heart suit",
    "♦" to "diamond suit",
    "♣" to "club suit",
    "♟" to "chess pawn",
    "🖼" to "framed picture",
    "👓" to "glasses",
    "🕶" to "sunglasses",
    "🥽" to "goggles",
    "🥼" to "lab coat",
    "🦺" to "safety vest",
    "👔" to "necktie",
    "👕" to "t shirt",
    "👖" to "jeans",
    "🧣" to "scarf",
    "🧤" to "gloves",
    "🧥" to "coat",
    "🧦" to "socks",
    "👗" to "dress",
    "👘" to "kimono",
    "🥻" to "sari",
    "🩱" to "one piece swimsuit",
    "🩲" to "briefs",
    "🩳" to "shorts",
    "👙" to "bikini",
    "👚" to "womans clothes",
    "🪭" to "folding hand fan",
    "👛" to "purse",
    "👜" to "handbag",
    "👝" to "clutch bag",
    "🛍" to "shopping bags",
    "🎒" to "backpack",
    "🩴" to "thong sandal",
    "👞" to "mans shoe",
    "👟" to "running shoe",
    "🥾" to "hiking boot",
    "🥿" to "flat shoe",
    "👠" to "high heeled shoe",
    "👡" to "womans sandal",
    "🩰" to "ballet shoes",
    "👢" to "womans boot",
    "🪮" to "hair pick",
    "👑" to "crown",
    "👒" to "womans hat",
    "🎩" to "top hat",
    "🎓" to "graduation cap",
    "🧢" to "billed cap",
    "🪖" to "military helmet",
    "⛑" to "rescue workers helmet",
    "📿" to "prayer beads",
    "💄" to "lipstick",
    "💍" to "ring",
    "💎" to "gem stone",
    "🔇" to "muted speaker",
    "🔈" to "speaker low volume",
    "🔉" to "speaker medium volume",
    "🔊" to "speaker high volume",
    "📢" to "loudspeaker",
    "📣" to "megaphone",
    "📯" to "postal horn",
    "🔔" to "bell",
    "🔕" to "bell with slash",
    "🎼" to "musical score",
    "🎵" to "musical note",
    "🎶" to "musical notes",
    "🎙" to "studio microphone",
    "🎚" to "level slider",
    "🎛" to "control knobs",
    "🎤" to "microphone",
    "🎧" to "headphone",
    "📻" to "radio",
    "🎷" to "saxophone",
    "🎺" to "trumpet",
    "🪗" to "accordion",
    "🎸" to "guitar",
    "🎹" to "musical keyboard",
    "🎻" to "violin",
    "🪕" to "banjo",
    "🥁" to "drum",
    "🪘" to "long drum",
    "🪇" to "maracas",
    "🪈" to "flute",
    "🪉" to "harp",
    "📱" to "mobile phone",
    "📲" to "mobile phone with arrow",
    "☎" to "telephone",
    "📞" to "telephone receiver",
    "📟" to "pager",
    "📠" to "fax machine",
    "🔋" to "battery",
    "🪫" to "low battery",
    "🔌" to "electric plug",
    "💻" to "laptop",
    "🖥" to "desktop computer",
    "🖨" to "printer",
    "⌨" to "keyboard",
    "🖱" to "computer mouse",
    "🖲" to "trackball",
    "💽" to "computer disk",
    "💾" to "floppy disk",
    "💿" to "optical disk",
    "📀" to "dvd",
    "🧮" to "abacus",
    "🎥" to "movie camera",
    "🎞" to "film frames",
    "📽" to "film projector",
    "🎬" to "clapper board",
    "📺" to "television",
    "📷" to "camera",
    "📸" to "camera with flash",
    "📹" to "video camera",
    "📼" to "videocassette",
    "🔍" to "magnifying glass tilted left",
    "🔎" to "magnifying glass tilted right",
    "🕯" to "candle",
    "💡" to "light bulb",
    "🔦" to "flashlight",
    "🏮" to "red paper lantern",
    "🪔" to "diya lamp",
    "📔" to "notebook with decorative cover",
    "📕" to "closed book",
    "📖" to "open book",
    "📗" to "green book",
    "📘" to "blue book",
    "📙" to "orange book",
    "📚" to "books",
    "📓" to "notebook",
    "📒" to "ledger",
    "📃" to "page with curl",
    "📜" to "scroll",
    "📄" to "page facing up",
    "📰" to "newspaper",
    "🗞" to "rolled up newspaper",
    "📑" to "bookmark tabs",
    "🔖" to "bookmark",
    "🏷" to "label",
    "🪙" to "coin",
    "💰" to "money bag",
    "💴" to "yen banknote",
    "💵" to "dollar banknote",
    "💶" to "euro banknote",
    "💷" to "pound banknote",
    "💸" to "money with wings",
    "💳" to "credit card",
    "🧾" to "receipt",
    "💹" to "chart increasing with yen",
    "✉" to "envelope",
    "📧" to "e mail",
    "📨" to "incoming envelope",
    "📩" to "envelope with arrow",
    "📤" to "outbox tray",
    "📥" to "inbox tray",
    "📦" to "package",
    "📫" to "closed mailbox with raised flag",
    "📪" to "closed mailbox with lowered flag",
    "📬" to "open mailbox with raised flag",
    "📭" to "open mailbox with lowered flag",
    "📮" to "postbox",
    "🗳" to "ballot box with ballot",
    "✏" to "pencil",
    "✒" to "black nib",
    "🖋" to "fountain pen",
    "🖊" to "pen",
    "🖌" to "paintbrush",
    "🖍" to "crayon",
    "📝" to "memo",
    "💼" to "briefcase",
    "📁" to "file folder",
    "📂" to "open file folder",
    "🗂" to "card index dividers",
    "📅" to "calendar",
    "📆" to "tear off calendar",
    "🗒" to "spiral notepad",
    "🗓" to "spiral calendar",
    "📇" to "card index",
    "📈" to "chart increasing",
    "📉" to "chart decreasing",
    "📊" to "bar chart",
    "📋" to "clipboard",
    "📌" to "pushpin",
    "📍" to "round pushpin",
    "📎" to "paperclip",
    "🖇" to "linked paperclips",
    "📏" to "straight ruler",
    "📐" to "triangular ruler",
    "✂" to "scissors",
    "🗃" to "card file box",
    "🗄" to "file cabinet",
    "🗑" to "wastebasket",
    "🔒" to "locked",
    "🔓" to "unlocked",
    "🔏" to "locked with pen",
    "🔐" to "locked with key",
    "🔑" to "key",
    "🗝" to "old key",
    "🔨" to "hammer",
    "🪓" to "axe",
    "⛏" to "pick",
    "⚒" to "hammer and pick",
    "🛠" to "hammer and wrench",
    "🗡" to "dagger",
    "⚔" to "crossed swords",
    "💣" to "bomb",
    "🪃" to "boomerang",
    "🏹" to "bow and arrow",
    "🛡" to "shield",
    "🪚" to "carpentry saw",
    "🔧" to "wrench",
    "🪛" to "screwdriver",
    "🔩" to "nut and bolt",
    "⚙" to "gear",
    "🗜" to "clamp",
    "⚖" to "balance scale",
    "🦯" to "white cane",
    "🔗" to "link",
    "⛓" to "chains",
    "🪝" to "hook",
    "🧰" to "toolbox",
    "🧲" to "magnet",
    "🪜" to "ladder",
    "🪏" to "shovel",
    "⚗" to "alembic",
    "🧪" to "test tube",
    "🧫" to "petri dish",
    "🧬" to "dna",
    "🔬" to "microscope",
    "🔭" to "telescope",
    "📡" to "satellite antenna",
    "💉" to "syringe",
    "🩸" to "drop of blood",
    "💊" to "pill",
    "🩹" to "adhesive bandage",
    "🩼" to "crutch",
    "🩺" to "stethoscope",
    "🩻" to "x ray",
    "🚪" to "door",
    "🛗" to "elevator",
    "🪞" to "mirror",
    "🪟" to "window",
    "🛏" to "bed",
    "🛋" to "couch and lamp",
    "🪑" to "chair",
    "🚽" to "toilet",
    "🪠" to "plunger",
    "🚿" to "shower",
    "🛁" to "bathtub",
    "🪤" to "mouse trap",
    "🪒" to "razor",
    "🧴" to "lotion bottle",
    "🧷" to "safety pin",
    "🧹" to "broom",
    "🧺" to "basket",
    "🧻" to "roll of paper",
    "🪣" to "bucket",
    "🧼" to "soap",
    "🫧" to "bubbles",
    "🪥" to "toothbrush",
    "🧽" to "sponge",
    "🧯" to "fire extinguisher",
    "🛒" to "shopping cart",
    "🚬" to "cigarette",
    "⚰" to "coffin",
    "🪦" to "headstone",
    "⚱" to "funeral urn",
    "🧿" to "nazar amulet",
    "🪬" to "hamsa",
    "🗿" to "moai",
    "🪧" to "placard",
    "🪪" to "identification card",
    "🏧" to "atm sign",
    "🚮" to "litter in bin sign",
    "🚰" to "potable water",
    "♿" to "wheelchair symbol",
    "🚹" to "mens room",
    "🚺" to "womens room",
    "🚻" to "restroom",
    "🚼" to "baby symbol",
    "🚾" to "water closet",
    "🛂" to "passport control",
    "🛃" to "customs",
    "🛄" to "baggage claim",
    "🛅" to "left luggage",
    "⚠" to "warning",
    "🚸" to "children crossing",
    "⛔" to "no entry",
    "🚫" to "prohibited",
    "🚳" to "no bicycles",
    "🚭" to "no smoking",
    "🚯" to "no littering",
    "🚱" to "non potable water",
    "🚷" to "no pedestrians",
    "📵" to "no mobile phones",
    "🔞" to "no one under eighteen",
    "☢" to "radioactive",
    "☣" to "biohazard",
    "⬆" to "up arrow",
    "↗" to "up right arrow",
    "➡" to "right arrow",
    "↘" to "down right arrow",
    "⬇" to "down arrow",
    "↙" to "down left arrow",
    "⬅" to "left arrow",
    "↖" to "up left arrow",
    "↕" to "up down arrow",
    "↔" to "left right arrow",
    "↩" to "right arrow curving left",
    "↪" to "left arrow curving right",
    "⤴" to "right arrow curving up",
    "⤵" to "right arrow curving down",
    "🔃" to "clockwise vertical arrows",
    "🔄" to "counterclockwise arrows button",
    "🔙" to "back arrow",
    "🔚" to "end arrow",
    "🔛" to "on! arrow",
    "🔜" to "soon arrow",
    "🔝" to "top arrow",
    "🛐" to "place of worship",
    "⚛" to "atom symbol",
    "🕉" to "om",
    "✡" to "star of david",
    "☸" to "wheel of dharma",
    "☯" to "yin yang",
    "✝" to "latin cross",
    "☦" to "orthodox cross",
    "☪" to "star and crescent",
    "☮" to "peace symbol",
    "🕎" to "menorah",
    "🔯" to "dotted six pointed star",
    "🪯" to "khanda",
    "♈" to "aries",
    "♉" to "taurus",
    "♊" to "gemini",
    "♋" to "cancer",
    "♌" to "leo",
    "♍" to "virgo",
    "♎" to "libra",
    "♏" to "scorpio",
    "♐" to "sagittarius",
    "♑" to "capricorn",
    "♒" to "aquarius",
    "♓" to "pisces",
    "⛎" to "ophiuchus",
    "🔀" to "shuffle tracks button",
    "🔁" to "repeat button",
    "🔂" to "repeat single button",
    "▶" to "play button",
    "⏩" to "fast forward button",
    "⏭" to "next track button",
    "⏯" to "play or pause button",
    "◀" to "reverse button",
    "⏪" to "fast reverse button",
    "⏮" to "last track button",
    "🔼" to "upwards button",
    "⏫" to "fast up button",
    "🔽" to "downwards button",
    "⏬" to "fast down button",
    "⏸" to "pause button",
    "⏹" to "stop button",
    "⏺" to "record button",
    "⏏" to "eject button",
    "🎦" to "cinema",
    "🔅" to "dim button",
    "🔆" to "bright button",
    "📶" to "antenna bars",
    "🛜" to "wireless",
    "📳" to "vibration mode",
    "📴" to "mobile phone off",
    "♀" to "female sign",
    "♂" to "male sign",
    "⚧" to "transgender symbol",
    "✖" to "multiply",
    "➕" to "plus",
    "➖" to "minus",
    "➗" to "divide",
    "🟰" to "heavy equals sign",
    "♾" to "infinity",
    "‼" to "double exclamation mark",
    "⁉" to "exclamation question mark",
    "❓" to "red question mark",
    "❔" to "white question mark",
    "❕" to "white exclamation mark",
    "❗" to "red exclamation mark",
    "〰" to "wavy dash",
    "💱" to "currency exchange",
    "💲" to "heavy dollar sign",
    "⚕" to "medical symbol",
    "♻" to "recycling symbol",
    "⚜" to "fleur de lis",
    "🔱" to "trident emblem",
    "📛" to "name badge",
    "🔰" to "japanese symbol for beginner",
    "⭕" to "hollow red circle",
    "✅" to "check mark button",
    "☑" to "check box with check",
    "✔" to "check mark",
    "❌" to "cross mark",
    "❎" to "cross mark button",
    "➰" to "curly loop",
    "➿" to "double curly loop",
    "〽" to "part alternation mark",
    "✳" to "eight spoked asterisk",
    "✴" to "eight pointed star",
    "❇" to "sparkle",
    "©" to "copyright",
    "®" to "registered",
    "™" to "trade mark",
    "🔴" to "red circle",
    "🟠" to "orange circle",
    "🟡" to "yellow circle",
    "🟢" to "green circle",
    "🔵" to "blue circle",
    "🟣" to "purple circle",
    "🟤" to "brown circle",
    "⚫" to "black circle",
    "⚪" to "white circle",
    "🟥" to "red square",
    "🟧" to "orange square",
    "🟨" to "yellow square",
    "🟩" to "green square",
    "🟦" to "blue square",
    "🟪" to "purple square",
    "🟫" to "brown square",
    "⬛" to "black large square",
    "⬜" to "white large square",
    "◼" to "black medium square",
    "◻" to "white medium square",
    "◾" to "black medium small square",
    "◽" to "white medium small square",
    "▪" to "black small square",
    "▫" to "white small square",
    "🔶" to "large orange diamond",
    "🔷" to "large blue diamond",
    "🔸" to "small orange diamond",
    "🔹" to "small blue diamond",
    "🔺" to "red triangle pointed up",
    "🔻" to "red triangle pointed down",
    "💠" to "diamond with a dot",
    "🔘" to "radio button",
    "🔳" to "white square button",
    "🔲" to "black square button",
    "🏁" to "chequered flag",
    "🚩" to "triangular flag",
    "🎌" to "crossed flags",
    "🏴" to "black flag",
    "🏳" to "white flag",
    "🇦🇨" to "flag: ascension island",
    "🇦🇩" to "flag: andorra",
    "🇦🇪" to "flag: united arab emirates",
    "🇦🇫" to "flag: afghanistan",
    "🇦🇬" to "flag: antigua & barbuda",
    "🇦🇮" to "flag: anguilla",
    "🇦🇱" to "flag: albania",
    "🇦🇲" to "flag: armenia",
    "🇦🇴" to "flag: angola",
    "🇦🇶" to "flag: antarctica",
    "🇦🇷" to "flag: argentina",
    "🇦🇸" to "flag: american samoa",
    "🇦🇹" to "flag: austria",
    "🇦🇺" to "flag: australia",
    "🇦🇼" to "flag: aruba",
    "🇦🇽" to "flag: åland islands",
    "🇦🇿" to "flag: azerbaijan",
    "🇧🇦" to "flag: bosnia & herzegovina",
    "🇧🇧" to "flag: barbados",
    "🇧🇩" to "flag: bangladesh",
    "🇧🇪" to "flag: belgium",
    "🇧🇫" to "flag: burkina faso",
    "🇧🇬" to "flag: bulgaria",
    "🇧🇭" to "flag: bahrain",
    "🇧🇮" to "flag: burundi",
    "🇧🇯" to "flag: benin",
    "🇧🇱" to "flag: st. barthélemy",
    "🇧🇲" to "flag: bermuda",
    "🇧🇳" to "flag: brunei",
    "🇧🇴" to "flag: bolivia",
    "🇧🇶" to "flag: caribbean netherlands",
    "🇧🇷" to "flag: brazil",
    "🇧🇸" to "flag: bahamas",
    "🇧🇹" to "flag: bhutan",
    "🇧🇻" to "flag: bouvet island",
    "🇧🇼" to "flag: botswana",
    "🇧🇾" to "flag: belarus",
    "🇧🇿" to "flag: belize",
    "🇨🇦" to "flag: canada",
    "🇨🇨" to "flag: cocos (keeling) islands",
    "🇨🇩" to "flag: congo   kinshasa",
    "🇨🇫" to "flag: central african republic",
    "🇨🇬" to "flag: congo   brazzaville",
    "🇨🇭" to "flag: switzerland",
    "🇨🇮" to "flag: côte divoire",
    "🇨🇰" to "flag: cook islands",
    "🇨🇱" to "flag: chile",
    "🇨🇲" to "flag: cameroon",
    "🇨🇳" to "flag: china",
    "🇨🇴" to "flag: colombia",
    "🇨🇵" to "flag: clipperton island",
    "🇨🇶" to "flag: sark",
    "🇨🇷" to "flag: costa rica",
    "🇨🇺" to "flag: cuba",
    "🇨🇻" to "flag: cape verde",
    "🇨🇼" to "flag: curaçao",
    "🇨🇽" to "flag: christmas island",
    "🇨🇾" to "flag: cyprus",
    "🇨🇿" to "flag: czechia",
    "🇩🇪" to "flag: germany",
    "🇩🇬" to "flag: diego garcia",
    "🇩🇯" to "flag: djibouti",
    "🇩🇰" to "flag: denmark",
    "🇩🇲" to "flag: dominica",
    "🇩🇴" to "flag: dominican republic",
    "🇩🇿" to "flag: algeria",
    "🇪🇦" to "flag: ceuta & melilla",
    "🇪🇨" to "flag: ecuador",
    "🇪🇪" to "flag: estonia",
    "🇪🇬" to "flag: egypt",
    "🇪🇭" to "flag: western sahara",
    "🇪🇷" to "flag: eritrea",
    "🇪🇸" to "flag: spain",
    "🇪🇹" to "flag: ethiopia",
    "🇪🇺" to "flag: european union",
    "🇫🇮" to "flag: finland",
    "🇫🇯" to "flag: fiji",
    "🇫🇰" to "flag: falkland islands",
    "🇫🇲" to "flag: micronesia",
    "🇫🇴" to "flag: faroe islands",
    "🇫🇷" to "flag: france",
    "🇬🇦" to "flag: gabon",
    "🇬🇧" to "flag: united kingdom",
    "🇬🇩" to "flag: grenada",
    "🇬🇪" to "flag: georgia",
    "🇬🇫" to "flag: french guiana",
    "🇬🇬" to "flag: guernsey",
    "🇬🇭" to "flag: ghana",
    "🇬🇮" to "flag: gibraltar",
    "🇬🇱" to "flag: greenland",
    "🇬🇲" to "flag: gambia",
    "🇬🇳" to "flag: guinea",
    "🇬🇵" to "flag: guadeloupe",
    "🇬🇶" to "flag: equatorial guinea",
    "🇬🇷" to "flag: greece",
    "🇬🇸" to "flag: south georgia & south sandwich islands",
    "🇬🇹" to "flag: guatemala",
    "🇬🇺" to "flag: guam",
    "🇬🇼" to "flag: guinea bissau",
    "🇬🇾" to "flag: guyana",
    "🇭🇰" to "flag: hong kong sar china",
    "🇭🇲" to "flag: heard & mcdonald islands",
    "🇭🇳" to "flag: honduras",
    "🇭🇷" to "flag: croatia",
    "🇭🇹" to "flag: haiti",
    "🇭🇺" to "flag: hungary",
    "🇮🇨" to "flag: canary islands",
    "🇮🇩" to "flag: indonesia",
    "🇮🇪" to "flag: ireland",
    "🇮🇱" to "flag: israel",
    "🇮🇲" to "flag: isle of man",
    "🇮🇳" to "flag: india",
    "🇮🇴" to "flag: british indian ocean territory",
    "🇮🇶" to "flag: iraq",
    "🇮🇷" to "flag: iran",
    "🇮🇸" to "flag: iceland",
    "🇮🇹" to "flag: italy",
    "🇯🇪" to "flag: jersey",
    "🇯🇲" to "flag: jamaica",
    "🇯🇴" to "flag: jordan",
    "🇯🇵" to "flag: japan",
    "🇰🇪" to "flag: kenya",
    "🇰🇬" to "flag: kyrgyzstan",
    "🇰🇭" to "flag: cambodia",
    "🇰🇮" to "flag: kiribati",
    "🇰🇲" to "flag: comoros",
    "🇰🇳" to "flag: st. kitts & nevis",
    "🇰🇵" to "flag: north korea",
    "🇰🇷" to "flag: south korea",
    "🇰🇼" to "flag: kuwait",
    "🇰🇾" to "flag: cayman islands",
    "🇰🇿" to "flag: kazakhstan",
    "🇱🇦" to "flag: laos",
    "🇱🇧" to "flag: lebanon",
    "🇱🇨" to "flag: st. lucia",
    "🇱🇮" to "flag: liechtenstein",
    "🇱🇰" to "flag: sri lanka",
    "🇱🇷" to "flag: liberia",
    "🇱🇸" to "flag: lesotho",
    "🇱🇹" to "flag: lithuania",
    "🇱🇺" to "flag: luxembourg",
    "🇱🇻" to "flag: latvia",
    "🇱🇾" to "flag: libya",
    "🇲🇦" to "flag: morocco",
    "🇲🇨" to "flag: monaco",
    "🇲🇩" to "flag: moldova",
    "🇲🇪" to "flag: montenegro",
    "🇲🇫" to "flag: st. martin",
    "🇲🇬" to "flag: madagascar",
    "🇲🇭" to "flag: marshall islands",
    "🇲🇰" to "flag: north macedonia",
    "🇲🇱" to "flag: mali",
    "🇲🇲" to "flag: myanmar (burma)",
    "🇲🇳" to "flag: mongolia",
    "🇲🇴" to "flag: macao sar china",
    "🇲🇵" to "flag: northern mariana islands",
    "🇲🇶" to "flag: martinique",
    "🇲🇷" to "flag: mauritania",
    "🇲🇸" to "flag: montserrat",
    "🇲🇹" to "flag: malta",
    "🇲🇺" to "flag: mauritius",
    "🇲🇻" to "flag: maldives",
    "🇲🇼" to "flag: malawi",
    "🇲🇽" to "flag: mexico",
    "🇲🇾" to "flag: malaysia",
    "🇲🇿" to "flag: mozambique",
    "🇳🇦" to "flag: namibia",
    "🇳🇨" to "flag: new caledonia",
    "🇳🇪" to "flag: niger",
    "🇳🇫" to "flag: norfolk island",
    "🇳🇬" to "flag: nigeria",
    "🇳🇮" to "flag: nicaragua",
    "🇳🇱" to "flag: netherlands",
    "🇳🇴" to "flag: norway",
    "🇳🇵" to "flag: nepal",
    "🇳🇷" to "flag: nauru",
    "🇳🇺" to "flag: niue",
    "🇳🇿" to "flag: new zealand",
    "🇴🇲" to "flag: oman",
    "🇵🇦" to "flag: panama",
    "🇵🇪" to "flag: peru",
    "🇵🇫" to "flag: french polynesia",
    "🇵🇬" to "flag: papua new guinea",
    "🇵🇭" to "flag: philippines",
    "🇵🇰" to "flag: pakistan",
    "🇵🇱" to "flag: poland",
    "🇵🇲" to "flag: st. pierre & miquelon",
    "🇵🇳" to "flag: pitcairn islands",
    "🇵🇷" to "flag: puerto rico",
    "🇵🇸" to "flag: palestinian territories",
    "🇵🇹" to "flag: portugal",
    "🇵🇼" to "flag: palau",
    "🇵🇾" to "flag: paraguay",
    "🇶🇦" to "flag: qatar",
    "🇷🇪" to "flag: réunion",
    "🇷🇴" to "flag: romania",
    "🇷🇸" to "flag: serbia",
    "🇷🇺" to "flag: russia",
    "🇷🇼" to "flag: rwanda",
    "🇸🇦" to "flag: saudi arabia",
    "🇸🇧" to "flag: solomon islands",
    "🇸🇨" to "flag: seychelles",
    "🇸🇩" to "flag: sudan",
    "🇸🇪" to "flag: sweden",
    "🇸🇬" to "flag: singapore",
    "🇸🇭" to "flag: st. helena",
    "🇸🇮" to "flag: slovenia",
    "🇸🇯" to "flag: svalbard & jan mayen",
    "🇸🇰" to "flag: slovakia",
    "🇸🇱" to "flag: sierra leone",
    "🇸🇲" to "flag: san marino",
    "🇸🇳" to "flag: senegal",
    "🇸🇴" to "flag: somalia",
    "🇸🇷" to "flag: suriname",
    "🇸🇸" to "flag: south sudan",
    "🇸🇹" to "flag: são tomé & príncipe",
    "🇸🇻" to "flag: el salvador",
    "🇸🇽" to "flag: sint maarten",
    "🇸🇾" to "flag: syria",
    "🇸🇿" to "flag: eswatini",
    "🇹🇦" to "flag: tristan da cunha",
    "🇹🇨" to "flag: turks & caicos islands",
    "🇹🇩" to "flag: chad",
    "🇹🇫" to "flag: french southern territories",
    "🇹🇬" to "flag: togo",
    "🇹🇭" to "flag: thailand",
    "🇹🇯" to "flag: tajikistan",
    "🇹🇰" to "flag: tokelau",
    "🇹🇱" to "flag: timor leste",
    "🇹🇲" to "flag: turkmenistan",
    "🇹🇳" to "flag: tunisia",
    "🇹🇴" to "flag: tonga",
    "🇹🇷" to "flag: türkiye",
    "🇹🇹" to "flag: trinidad & tobago",
    "🇹🇻" to "flag: tuvalu",
    "🇹🇼" to "flag: taiwan",
    "🇹🇿" to "flag: tanzania",
    "🇺🇦" to "flag: ukraine",
    "🇺🇬" to "flag: uganda",
    "🇺🇲" to "flag: u.s. outlying islands",
    "🇺🇳" to "flag: united nations",
    "🇺🇸" to "flag: united states",
    "🇺🇾" to "flag: uruguay",
    "🇺🇿" to "flag: uzbekistan",
    "🇻🇦" to "flag: vatican city",
    "🇻🇨" to "flag: st. vincent & grenadines",
    "🇻🇪" to "flag: venezuela",
    "🇻🇬" to "flag: british virgin islands",
    "🇻🇮" to "flag: u.s. virgin islands",
    "🇻🇳" to "flag: vietnam",
    "🇻🇺" to "flag: vanuatu",
    "🇼🇫" to "flag: wallis & futuna",
    "🇼🇸" to "flag: samoa",
    "🇽🇰" to "flag: kosovo",
    "🇾🇪" to "flag: yemen",
    "🇾🇹" to "flag: mayotte",
    "🇿🇦" to "flag: south africa",
    "🇿🇲" to "flag: zambia",
    "🇿🇼" to "flag: zimbabwe",
    "👋" to "waving hand",
    "🤚" to "raised back of hand",
    "🖐" to "hand with fingers splayed",
    "✋" to "raised hand",
    "🖖" to "vulcan salute",
    "🫱" to "rightwards hand",
    "🫲" to "leftwards hand",
    "🫳" to "palm down hand",
    "🫴" to "palm up hand",
    "🫷" to "leftwards pushing hand",
    "🫸" to "rightwards pushing hand",
    "👌" to "ok hand",
    "🤌" to "pinched fingers",
    "🤏" to "pinching hand",
    "✌" to "victory hand",
    "🤞" to "crossed fingers",
    "🫰" to "hand with index finger and thumb crossed",
    "🤟" to "love you gesture",
    "🤘" to "sign of the horns",
    "🤙" to "call me hand",
    "👈" to "backhand index pointing left",
    "👉" to "backhand index pointing right",
    "👆" to "backhand index pointing up",
    "🖕" to "middle finger",
    "👇" to "backhand index pointing down",
    "☝" to "index pointing up",
    "🫵" to "index pointing at the viewer",
    "👍" to "thumbs up",
    "👎" to "thumbs down",
    "✊" to "raised fist",
    "👊" to "oncoming fist",
    "🤛" to "left facing fist",
    "🤜" to "right facing fist",
    "👏" to "clapping hands",
    "🙌" to "raising hands",
    "🫶" to "heart hands",
    "👐" to "open hands",
    "🤲" to "palms up together",
    "🤝" to "handshake",
    "🙏" to "folded hands",
    "✍" to "writing hand",
    "💅" to "nail polish",
    "🤳" to "selfie",
    "💪" to "flexed biceps",
    "🦾" to "mechanical arm",
    "🦿" to "mechanical leg",
    "🦵" to "leg",
    "🦶" to "foot",
    "👂" to "ear",
    "🦻" to "ear with hearing aid",
    "👃" to "nose",
    "🧠" to "brain",
    "🫀" to "anatomical heart",
    "🫁" to "lungs",
    "🦷" to "tooth",
    "🦴" to "bone",
    "👀" to "eyes",
    "👁" to "eye",
    "👅" to "tongue",
    "👄" to "mouth",
    "🫦" to "biting lip",
    "🫪" to "distorted face anxiety bloated panic shocked surprised vulnerable",
    "🫯" to "fight cloud argument brawl debate disagreement fight ruckus wrestle",
    "🫈" to "hairy creature bigfoot cryptid forest giant hairy sasquatch woodwose yeti",
    "🧑‍🩰" to "ballet dancer ballet dancer graceful perform twirl",
    "👯" to "people with bunny ears bestie bff bunny counterpart dancer double ear identical pair party partying people soulmate twin twinsies",
    "🤼" to "people wrestling combat duel grapple people ring tournament wrestle wrestling",
    "🫍" to "orca marine ocean whale",
    "🛘" to "landslide avalanche danger disaster earthquake mountain mudslide rocks",
    "🪊" to "trombone brass instrument jazz music sad slide",
    "🪎" to "treasure chest gem gold jewels loot money prize silver valuables wealth",
)
